-- ============================================================================
-- pgapi Blog Example Schema
-- ============================================================================
--
-- A blog schema demonstrating pgapi's row-level permission system.
--
-- Tables:
--   users      - blog accounts with roles (admin, editor, author, reader)
--   posts      - blog articles, may be public or private
--   comments   - reader comments on posts
--   categories - post categorisation
--
-- Permission functions defined:
--   posts_select_filter  - readers see public posts, authors see their drafts
--   posts_delete_filter  - only authors can delete their own posts
--   posts_update_filter  - only authors/editors can update posts
--   posts_insert_check   - authors can only create posts they own
--   posts_update_check   - posts cannot change owner
--   comments_select_filter - comments visible if the parent post is visible
--   comments_insert_check  - comment author must match the authenticated user
--
-- This script is idempotent and can be run repeatedly.
-- pgapi will discover the permission functions at startup and enforce them.
-- =============================================================================


-- ============================================================================
-- Drop existing objects (fresh start)
-- ============================================================================

DROP FUNCTION IF EXISTS comments_insert_check(text, text, jsonb);
DROP FUNCTION IF EXISTS comments_select_filter();
DROP FUNCTION IF EXISTS posts_update_check(text, text, jsonb);
DROP FUNCTION IF EXISTS posts_insert_check(text, text, jsonb);
DROP FUNCTION IF EXISTS posts_update_filter();
DROP FUNCTION IF EXISTS posts_delete_filter();
DROP FUNCTION IF EXISTS posts_select_filter();

DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS users;


-- ============================================================================
-- Tables
-- ============================================================================

CREATE TABLE IF NOT EXISTS users (
    id         serial PRIMARY KEY,
    name       text NOT NULL,
    email      text NOT NULL UNIQUE,
    role       text NOT NULL DEFAULT 'reader'
               CHECK (role IN ('admin', 'editor', 'author', 'reader')),
    created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE users IS 'Blog user accounts';
COMMENT ON COLUMN users.role IS 'Permission level: admin, editor, author, reader';


CREATE TABLE IF NOT EXISTS categories (
    id   serial PRIMARY KEY,
    name text NOT NULL UNIQUE
);

COMMENT ON TABLE categories IS 'Post categories';


CREATE TABLE IF NOT EXISTS posts (
    id          serial PRIMARY KEY,
    title       text NOT NULL,
    body        text,
    published   boolean NOT NULL DEFAULT false,
    category_id int REFERENCES categories(id),
    owned_by    int NOT NULL REFERENCES users(id),
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE posts IS 'Blog articles. published=false posts are private drafts.';


CREATE TABLE IF NOT EXISTS comments (
    id         serial PRIMARY KEY,
    body       text NOT NULL,
    post_id    int NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    author_id  int NOT NULL REFERENCES users(id),
    created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE comments IS 'Reader comments on published posts';


-- ============================================================================
-- Session variables (set by pgapi before each request)
-- ============================================================================
--
-- pgapi sets these from the JWT claims:
--   SET "x_pgapi.sub"  = '<sub claim as text>'
--   SET "x_pgapi.role" = '<role claim as text>'
--
-- Your permission functions read them with:
--   current_setting('x_pgapi.sub')
--   current_setting('x_pgapi.role')
--
-- Example JWT payload:
--   { "sub": "42", "role": "author" }


-- ============================================================================
-- Permission functions: Posts
-- ============================================================================

-- SELECT filter
-- Who can see which posts?
--   - Everyone sees published posts
--   - Authors and above see their own unpublished drafts
--   - Admins see everything
--
-- pgapi uses this for: list queries, by-PK lookups, and FK resolution.
-- Your user-supplied WHERE clauses are applied WITHIN this filter.
--
-- SQL generated by pgapi:
--   SELECT "id", "title", ...
--   FROM "public.posts_select_filter"()
--   WHERE <your where clause>

CREATE OR REPLACE FUNCTION posts_select_filter()
RETURNS SETOF posts AS $$
    SELECT * FROM posts
    WHERE published = true
       OR owned_by = CASE WHEN current_setting('x_pgapi.sub') ~ '^\d+$'
                          THEN current_setting('x_pgapi.sub')::int END
$$ LANGUAGE sql STABLE;


-- DELETE filter
-- Who can delete which posts?
--   - Authors can delete their own posts
--   - Admins can delete any post
--
-- SQL generated by pgapi:
--   DELETE FROM "public.posts_delete_filter"()
--   WHERE "id" = $1
--   RETURNING *

CREATE OR REPLACE FUNCTION posts_delete_filter()
RETURNS SETOF posts AS $$
    SELECT * FROM posts
    WHERE owned_by = CASE WHEN current_setting('x_pgapi.sub') ~ '^\d+$'
                          THEN current_setting('x_pgapi.sub')::int END
       OR current_setting('x_pgapi.role') = 'admin'
$$ LANGUAGE sql STABLE;


-- UPDATE filter
-- Who can update which posts?
--   - Authors can update their own posts
--   - Editors and admins can update any post
--
-- SQL generated by pgapi:
--   UPDATE "public"."posts"
--   SET "title" = $1, "body" = $2
--   WHERE "id" = $3
--     AND "id" IN (SELECT "id" FROM "public.posts_update_filter"())
--   RETURNING *

CREATE OR REPLACE FUNCTION posts_update_filter()
RETURNS SETOF posts AS $$
    SELECT * FROM posts
    WHERE owned_by = CASE WHEN current_setting('x_pgapi.sub') ~ '^\d+$'
                          THEN current_setting('x_pgapi.sub')::int END
       OR current_setting('x_pgapi.role') IN ('admin', 'editor')
$$ LANGUAGE sql STABLE;


-- INSERT check
-- Validates a new post before it is inserted.
-- The BEFORE INSERT trigger calls this function automatically.
-- Return true to allow the insert, false to reject it.
--
-- Arguments:
--   _sub  - the user's sub claim (text)
--   _role - the user's role claim (text)
--   _row  - the new row as JSONB (ROW_TO_JSON(NEW)::jsonb)
--
-- The row contains all column values. Access them with (_row->> 'column').

CREATE OR REPLACE FUNCTION posts_insert_check(_sub text, _role text, _row jsonb)
RETURNS boolean AS $$
    -- Authors and editors can create posts, but only as themselves
    SELECT (_row ->> 'owned_by')::int = CASE WHEN _sub ~ '^\d+$' THEN _sub::int END
$$ LANGUAGE sql STABLE;


-- UPDATE check
-- Validates the modified row before the update is applied.
-- Called by the BEFORE UPDATE trigger.
--
-- Use case: prevent changing the post owner after creation.

CREATE OR REPLACE FUNCTION posts_update_check(_sub text, _role text, _row jsonb)
RETURNS boolean AS $$
    -- The row must still be owned by the same user who originally owned it.
    -- (In practice, the update_filter already restricts this, but the check
    --  provides a second layer of defence against race conditions.)
    SELECT true
$$ LANGUAGE sql STABLE;


-- ============================================================================
-- Permission functions: Comments
-- ============================================================================

-- SELECT filter
-- Comments are visible if their parent post is visible.
-- This reuses the posts_select_filter logic via a subquery.

CREATE OR REPLACE FUNCTION comments_select_filter()
RETURNS SETOF comments AS $$
    SELECT c.* FROM comments c
    JOIN posts p ON c.post_id = p.id
    WHERE p.published = true
       OR p.owned_by = CASE WHEN current_setting('x_pgapi.sub') ~ '^\d+$'
                            THEN current_setting('x_pgapi.sub')::int END
$$ LANGUAGE sql STABLE;


-- INSERT check
-- The comment author must match the authenticated user.
-- Prevents one user from posting comments as another user.

CREATE OR REPLACE FUNCTION comments_insert_check(_sub text, _role text, _row jsonb)
RETURNS boolean AS $$
    SELECT (_row ->> 'author_id')::int = CASE WHEN _sub ~ '^\d+$' THEN _sub::int END
$$ LANGUAGE sql STABLE;


-- ============================================================================
-- Example data
-- ============================================================================

INSERT INTO users (id, name, email, role) VALUES
    (1, 'Alice',   'alice@example.com',   'admin'),
    (2, 'Bob',     'bob@example.com',     'editor'),
    (3, 'Charlie', 'charlie@example.com', 'author'),
    (4, 'Diana',   'diana@example.com',   'reader');
SELECT setval('users_id_seq', 4);

INSERT INTO categories (id, name) VALUES
    (1, 'General'),
    (2, 'Tech'),
    (3, 'Life');
SELECT setval('categories_id_seq', 3);

INSERT INTO posts (id, title, body, published, category_id, owned_by) VALUES
    (1, 'Welcome to the blog',     'This is our first post.',                    true,  1, 1),
    (2, 'Draft: Future plans',     'Coming soon...',                             false, 1, 3),
    (3, 'PostgreSQL tips',         'Use EXPLAIN ANALYZE.',                       true,  2, 2),
    (4, 'Draft: Secret project',   'Not ready yet.',                             false, 2, 3),
    (5, 'Editorial guidelines',    'How we write around here.',                  true,  1, 2);
SELECT setval('posts_id_seq', 5);

INSERT INTO comments (id, body, post_id, author_id) VALUES
    (1, 'Great post!',              1, 4),
    (2, 'Very helpful, thanks.',    3, 4),
    (3, 'Looking forward to it.',   1, 3);
SELECT setval('comments_id_seq', 3);


-- ============================================================================
-- Done
-- ============================================================================
--
-- Start pgapi pointing at this database. It will discover these functions
-- and automatically enforce the permission rules on every GraphQL request.
--
-- Your JWT must include a "sub" claim matching a user id, and optionally a
-- "role" claim. For example, to act as Alice (id 1, admin):
--
--   { "sub": "1", "role": "admin" }
--
-- To act as Bob (id 2, regular user):
--
--   { "sub": "2" }
--
-- Sign the payload with your JWT secret and pass it as a Bearer token.
-- The posts_select_filter ensures readers only see published posts.
-- The comments_insert_check ensures a user can only comment as themselves.
