import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

const nmDir = join(import.meta.dir, "..", "node_modules");

const files: Record<string, string> = {
  react_js: join(nmDir, "react", "umd", "react.production.min.js"),
  react_dom_js: join(nmDir, "react-dom", "umd", "react-dom.production.min.js"),
  graphiql_js: join(nmDir, "graphiql", "graphiql.min.js"),
  graphiql_css: join(nmDir, "graphiql", "graphiql.min.css"),
};

const parts: string[] = ["// Auto-generated by scripts/embed-assets.ts — do not edit"];
for (const [name, filePath] of Object.entries(files)) {
  const content = readFileSync(filePath);
  parts.push(`export const ${name} = Buffer.from("${content.toString("base64")}", "base64");`);
}

writeFileSync(join(import.meta.dir, "..", "src", "static-assets.ts"), parts.join("\n") + "\n");
